const AppConstant = {
  onboard: 'Onboarding',
  chatList: 'ChatList',
  createAvatar: 'CreateAvatar',
  start: 'AuthStart',
  login: 'Login',
  signup: 'SignUp',
  forgot: 'ForgotPassword',
  mainNav: 'MainNavigation',
  home: 'Home',
  avatarDetail: 'AvatarDetail',
  chat: 'Chat',
  voiceCall: 'VoiceCall',
  personalInfo: 'PersonalInfo',
  ChangePassword: 'ChangePassword',
  helpCenter: 'HelpCenter',
  privacyPolicy: 'PrivacyPolicy',
  termsAndConditions: 'TermsAndConditions',
  account: 'Account',
  favorite: 'FavoriteAvatars',
  myAvatar: 'MyAvatar',
  createAvatarStep0: 'CreateAvatarStep0',
  createAvatarStep1: 'CreateAvatarStep1',
  createAvatarStep2: 'CreateAvatarStep2',
  createAvatarStep3: 'CreateAvatarStep3',
  createAvatarStep4: 'CreateAvatarStep4',
  createAvatarStep5: 'CreateAvatarStep5',
  createAvatarStep6: 'CreateAvatarStep6',
  createAvatarStep7: 'CreateAvatarStep7',
  createAvatarStep8: 'CreateAvatarStep8',
  createAvatarStep9: 'CreateAvatarStep9',
  createAvatarStep10: 'CreateAvatarStep10',
  createAvatarStep11: 'CreateAvatarStep11',
  createAvatarStep12: 'CreateAvatarStep12',
};

export default AppConstant;
